import { createFileRoute } from "@tanstack/react-router";
import { AppShell } from "@/components/layout/AppShell";
import { IntelligenceNav } from "@/components/intelligence/IntelligenceNav";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ClipboardList, Download } from "lucide-react";
import { useShiftHandoff } from "@/intelligence/hooks/useIntelligence";

export const Route = createFileRoute("/intelligence/handoff")({
  head: () => ({ meta: [{ title: "Shift Handoff — Anderoute Intelligence" }] }),
  component: HandoffPage,
});

function HandoffPage() {
  const { handoff } = useShiftHandoff();
  return (
    <AppShell>
      <div className="space-y-6">
        <header className="space-y-3">
          <div className="flex items-center gap-3">
            <ClipboardList className="size-5 text-emerald-300" />
            <h1 className="text-xl font-semibold">Shift Handoff Assistant</h1>
            <Badge variant="outline" className="border-white/15 text-muted-foreground">{handoff.shift_label}</Badge>
          </div>
          <IntelligenceNav />
        </header>

        <Card className="border-white/10 bg-white/[0.02] p-5">
          <div className="flex items-start justify-between gap-3">
            <div>
              <h2 className="text-base font-semibold">Generated by {handoff.generated_by}</h2>
              <p className="text-xs text-muted-foreground">{new Date(handoff.generated_at).toLocaleString()}</p>
            </div>
            <Button size="sm" variant="outline"><Download className="mr-1 size-3.5" /> Export</Button>
          </div>

          <div className="mt-4 grid gap-3 md:grid-cols-3 lg:grid-cols-6">
            <Mini label="Active loads" value={handoff.active_loads} />
            <Mini label="At risk" value={handoff.at_risk_loads} tone="rose" />
            <Mini label="Delayed drivers" value={handoff.delayed_drivers} tone="amber" />
            <Mini label="On break" value={handoff.drivers_on_break} />
            <Mini label="Off duty" value={handoff.drivers_off_duty} />
            <Mini label="Awaiting assign" value={handoff.loads_awaiting_assignment} tone="amber" />
          </div>

          <div className="mt-5 grid gap-4 md:grid-cols-2">
            <Section title="Priority actions" items={handoff.priority_actions} />
            <Section title="Recommended next steps" items={handoff.recommended_next_steps} />
            <Section title="Customer issues" items={handoff.customer_issues} />
            <Section title="EDI / API issues" items={handoff.edi_api_issues} />
            <Section title="Weather & traffic notes" items={handoff.weather_traffic_notes} />
          </div>
        </Card>
      </div>
    </AppShell>
  );
}

function Mini({ label, value, tone }: { label: string; value: number; tone?: string }) {
  const TONE: Record<string, string> = { rose: "text-rose-300", amber: "text-amber-300" };
  return (
    <div className="rounded border border-white/10 bg-black/20 p-3">
      <div className="text-[10px] uppercase text-muted-foreground">{label}</div>
      <div className={`text-xl font-semibold ${tone ? TONE[tone] : "text-foreground"}`}>{value}</div>
    </div>
  );
}

function Section({ title, items }: { title: string; items: string[] }) {
  return (
    <div>
      <div className="text-xs font-medium text-muted-foreground">{title}</div>
      <ul className="mt-1 space-y-1 text-sm">
        {items.length === 0 && <li className="text-xs text-muted-foreground">None.</li>}
        {items.map((i) => <li key={i}>• {i}</li>)}
      </ul>
    </div>
  );
}
