import * as D from "./data/mockPhase43";
import * as P from "./data/mockPhase43Polish";

export const useV15Scope = () => D.V15_SCOPE;
export const useV15FeatureMatrix = () => D.V15_FEATURES;
export const useEnterprisePerformanceCommand = () => D.V15_COMMAND;
export const useV15Trends = () => D.V15_TRENDS;
export const useDurableCapitalExecution = () => D.V15_CAPITAL;
export const useDurableRevenuePerformance = () => D.V15_REVENUE;
export const useMarketplaceScaleGovernance = () => D.V15_MP_GOV;
export const useMarketplaceScaleIntelligence = () => D.V15_MP_INTEL;
export const useStrategicOperatingIntelligence = () => D.V15_INTEL;
export const useOperatingIntelligenceRecommendations = () => D.V15_RECS;
export const useCategoryLeadershipOperatingSystem = () => D.V15_CATEGORY;
export const useExecutivePerformanceControl = () => D.V15_EXEC;
export const useBoardEnterpriseIntelligence = () => D.V15_BOARD;
export const useStrategicAccountPerformance = () => D.V15_ACCOUNTS;
export const usePartnerEcosystemPerformance = () => D.V15_PARTNERS;
export const useProductLinePerformanceGovernance = () => D.V15_PRODUCT_LINES;
export const useCapitalEvidenceGovernance = () => D.V15_EVIDENCE;
export const useCommercialDiligenceGovernance = () => D.V15_DILIGENCE;
export const useStrategicRiskIntelligence = () => D.V15_RISKS;
export const useEnterprisePerformanceControls = () => D.V15_CONTROLS;
export const useStrategicPerformanceRoadmap = () => D.V15_ROADMAP;
export const useBoardEnterprisePerformanceReporting = () => D.V15_BOARD;
export const useReportsV15 = () => D.V15_REPORTS;
export const useV15EdgeVsServerFn = () => D.V15_EDGE_VS_SERVERFN;
export const useV15Rls = () => D.V15_RLS_EXAMPLES;
export const useV15RlsSql = () => D.V15_RLS_SQL;
export const useV15Demo = () => D.V15_DEMO;
export const useV15DemoOutcomes = () => D.V15_DEMO_OUTCOMES;
export const useV15Phase44Teaser = () => D.V15_PHASE44_TEASER;
export const useV15ExecHeadline = () => D.V15_EXEC_HEADLINE;

// Phase 43 polish hooks
export const useV15AreaHeadlines = () => P.V15P_AREA_HEADLINES;
export const useV15OwnerHeatmap = () => P.V15P_OWNER_HEATMAP;
export const useV15ControlCoverage = () => P.V15P_CONTROL_COVERAGE;
export const useV15RlsExtended = () => P.V15P_RLS_EXTENDED;
export const useV15EdgeExtended = () => P.V15P_EDGE_EXTENDED;
export const useV15DemoFlowPolish = () => P.V15P_DEMO_FLOW;
export const useV15DemoOutcomesPolish = () => P.V15P_DEMO_OUTCOMES;
export const useV15Phase44Hold = () => P.V15P_PHASE44_HOLD;
