// V5.5 hooks — mock-only, ready for serverFn wiring later.
import * as M from "./data/mockPhase24";

export const useV55Scope                       = () => ({ matrix: M.V55_FEATURE_MATRIX, deferred: M.V55_DEFERRED, score: M.LEADERSHIP.overall });
export const useLeadershipAlerts               = () => ({ alerts: M.LEADERSHIP_ALERTS });
export const useDefensibilityTrend             = () => ({ trend: M.DEFENSIBILITY_TREND });
export const useMonetizationTrend              = () => ({ trend: M.MONETIZATION_TREND });
export const useBoardTrends                    = () => ({ trends: M.BOARD_TRENDS });
export const useRetentionTrend                 = () => ({ trend: M.RETENTION_TREND });
export const useReliabilityTrend               = () => ({ trend: M.RELIABILITY_TREND });
export const useCompetitiveWinRate             = () => ({ stats: M.COMPETITIVE_WIN_RATE });
export const useCategoryProofHighlights        = () => ({ points: M.CATEGORY_PROOF_HIGHLIGHTS });
export const useDataRoomProgress               = () => M.DATA_ROOM_PROGRESS();
export const useMarketLeadership               = () => ({ leadership: M.LEADERSHIP, trend: M.LEADERSHIP_TREND, gaps: M.LEADERSHIP_GAPS });
export const usePlatformDefensibility          = () => ({ defensibility: M.DEFENSIBILITY });
export const useStrategicMoats                 = () => ({ moats: M.MOATS });
export const useEcosystemMonetization          = () => ({ lines: M.REVENUE_LINES, score: M.MONETIZATION_SCORE });
export const useMarketplaceEconomics           = () => ({ kpis: M.MP_ECONOMICS, trend: M.MP_ECONOMICS_TREND });
export const useNationalPartnerships           = () => ({ partners: M.NATIONAL_PARTNERSHIPS });
export const usePartnerEcosystemScale          = () => ({ scale: M.PARTNER_ECOSYSTEM });
export const useEnterpriseOperatingModel       = () => ({ fns: M.OPERATING_FUNCTIONS });
export const useExecutiveOperatingCadence      = () => ({ cadences: M.OPERATING_CADENCES, decisions: M.EXEC_DECISIONS });
export const useBoardInvestorReporting         = () => ({ report: M.BOARD_REPORT });
export const useProductLineMaturity            = () => ({ lines: M.PRODUCT_LINES });
export const useRetentionExpansion             = () => ({ accounts: M.RETENTION_ACCOUNTS, opps: M.EXPANSION_OPPS });
export const useEnterpriseAccountPlans         = () => ({ plans: M.ACCOUNT_PLANS });
export const useCategoryNarrative              = () => ({ narrative: M.CATEGORY_NARRATIVE });
export const useCompetitiveDifferentiation     = () => ({ competitors: M.COMPETITORS, winLoss: M.WIN_LOSS });
export const useCertificationEvidenceMaturity  = () => ({ evidence: M.CERT_EVIDENCE });
export const useSecurityComplianceExecutiveView= () => ({ items: M.SEC_EXEC });
export const useStrategicRiskManagement        = () => ({ risks: M.STRATEGIC_RISKS });
export const useLongTermRoadmapGovernance      = () => ({ items: M.ROADMAP, decisions: M.ROADMAP_DECISIONS });
export const useAdvancedDataRoom               = () => ({ items: M.DATA_ROOM, requests: M.DD_REQUESTS });
export const usePlatformReliabilityLeadership  = () => ({ metrics: M.RELIABILITY });
export const useReportsV55                     = () => ({ reports: M.V55_REPORTS });
