import type { Contact, Message } from "./types";

export const seedContacts: Contact[] = [
  // Channels
  {
    id: "ch-dispatch",
    kind: "channel",
    name: "dispatch-command",
    role: "Dispatcher",
    preview: "Weather delay on I-35 — re-routing 4 loads.",
    time: "05:42 PM",
    unread: 7,
    pinned: true,
    avatar: "",
    category: "dispatch",
    online: true,
    priority: "important",
    channelTopic: "Primary dispatch ops · 24/7",
  },
  {
    id: "ch-active-loads",
    kind: "channel",
    name: "active-loads",
    role: "Dispatcher",
    preview: "LD-1048 ETA updated to 42 min",
    time: "05:31 PM",
    unread: 3,
    pinned: true,
    avatar: "",
    category: "active_loads",
    online: true,
    channelTopic: "Live in-transit loads",
  },
  {
    id: "ch-delayed",
    kind: "channel",
    name: "delayed-routes",
    role: "Dispatcher",
    preview: "2 routes flagged: weather + dock hold",
    time: "04:58 PM",
    unread: 2,
    avatar: "",
    category: "dispatch",
    priority: "urgent",
    channelTopic: "Route exception monitoring",
  },
  {
    id: "ch-warehouse",
    kind: "channel",
    name: "warehouse-updates",
    role: "Warehouse",
    preview: "Dock 4 open — appointments through 18:00",
    time: "04:11 PM",
    unread: 0,
    avatar: "",
    category: "dispatch",
    channelTopic: "All hubs · dock + receiving",
  },
  {
    id: "ch-driver-support",
    kind: "channel",
    name: "driver-support",
    role: "Driver",
    preview: "Marcus: HOS reset needed",
    time: "03:55 PM",
    unread: 1,
    avatar: "",
    category: "support",
    channelTopic: "Driver hotline",
  },
  {
    id: "ch-invoice",
    kind: "channel",
    name: "invoice-requests",
    role: "Broker",
    preview: "Whitlow: rate con signed for LD-1052",
    time: "Yesterday",
    unread: 0,
    avatar: "",
    category: "invoices",
    channelTopic: "Billing + rate cons",
  },
  {
    id: "ch-customer",
    kind: "channel",
    name: "customer-service",
    role: "Customer",
    preview: "Sarah: delivery window question",
    time: "Yesterday",
    unread: 0,
    avatar: "",
    category: "support",
    channelTopic: "Customer-facing inbox",
  },
  {
    id: "ch-emergency",
    kind: "channel",
    name: "emergency-alerts",
    role: "Dispatcher",
    preview: "All-clear: weather advisory lifted",
    time: "11:02 AM",
    unread: 0,
    avatar: "",
    category: "dispatch",
    priority: "emergency",
    channelTopic: "Critical incidents only",
  },

  // Load chats
  {
    id: "load-ld1048",
    kind: "load",
    name: "LD-1048 · Austin → Dallas",
    role: "Dispatcher",
    preview: "ETA updated to 42 min",
    time: "Now",
    unread: 1,
    pinned: true,
    avatar: "",
    category: "active_loads",
    online: true,
    priority: "important",
    linkedLoad: {
      id: "LD-1048",
      origin: "Austin, TX",
      destination: "Dallas, TX",
      status: "In Transit",
      eta: "42 min",
    },
  },
  {
    id: "load-ld1052",
    kind: "load",
    name: "LD-1052 · Houston → Atlanta",
    role: "Dispatcher",
    preview: "Broker confirmed pickup window",
    time: "04:22 PM",
    unread: 0,
    avatar: "",
    category: "active_loads",
    linkedLoad: {
      id: "LD-1052",
      origin: "Houston, TX",
      destination: "Atlanta, GA",
      status: "At Pickup",
      eta: "—",
    },
  },

  // DMs
  {
    id: "marcus",
    kind: "dm",
    name: "Marcus Reed",
    role: "Driver",
    company: "Anderoute Fleet",
    preview: "I'm 12 minutes from dropoff",
    time: "05:18 PM",
    unread: 2,
    pinned: true,
    online: true,
    avatar: "https://i.pravatar.cc/80?img=12",
    category: "active_loads",
    linkedLoad: {
      id: "LD-1048",
      origin: "Austin, TX",
      destination: "Dallas, TX",
      status: "In Transit",
      eta: "12 min",
    },
  },
  {
    id: "harrold",
    kind: "dm",
    name: "Harrold Tafoya",
    role: "Carrier",
    company: "PSP Cargo Group",
    preview: "Can you send updated BOL?",
    time: "05:11 PM",
    unread: 0,
    typing: true,
    online: true,
    avatar: "https://i.pravatar.cc/80?img=14",
    category: "active_loads",
  },
  {
    id: "dallas-dock",
    kind: "dm",
    name: "Dallas DC Dock 4",
    role: "Warehouse",
    company: "Anderoute Dallas Hub",
    preview: "Dock door is open",
    time: "05:02 PM",
    unread: 0,
    online: true,
    avatar: "https://i.pravatar.cc/80?img=58",
    category: "dispatch",
  },
  {
    id: "sarah",
    kind: "dm",
    name: "Sarah Milton",
    role: "Customer",
    company: "Milton Retail Co.",
    preview: "Can we adjust delivery window?",
    time: "04:47 PM",
    unread: 1,
    avatar: "https://i.pravatar.cc/80?img=45",
    category: "support",
  },
  {
    id: "shannon",
    kind: "dm",
    name: "Shannon Kile",
    role: "Driver",
    preview: "Voice note · 0:14",
    time: "04:01 PM",
    unread: 1,
    online: true,
    avatar: "https://i.pravatar.cc/80?img=47",
    category: "active_loads",
  },
  {
    id: "jane",
    kind: "dm",
    name: "Jane Whitlow",
    role: "Broker",
    company: "Whitlow Logistics",
    preview: "Confirmed rate on lane.",
    time: "Yesterday",
    unread: 0,
    avatar: "https://i.pravatar.cc/80?img=49",
    category: "invoices",
  },
  {
    id: "nisa",
    kind: "dm",
    name: "Nisa Cordial",
    role: "Courier",
    preview: "Final mile completed",
    time: "Yesterday",
    unread: 0,
    avatar: "https://i.pravatar.cc/80?img=44",
    category: "completed",
  },
  {
    id: "wenston",
    kind: "dm",
    name: "Wenston Covil",
    role: "Driver",
    preview: "Can I fill up here? Location",
    time: "Dec 18",
    unread: 0,
    avatar: "https://i.pravatar.cc/80?img=17",
    category: "archived",
  },
];

export const seedMessages: Record<string, Message[]> = {
  marcus: [
    {
      id: "m-sys-1",
      kind: "system",
      from: "them",
      time: "—",
      text: "Marcus picked up load LD-1048 at Austin DC · 02:14 PM",
      icon: "check",
    },
    {
      id: "m1",
      kind: "text",
      from: "them",
      authorName: "Marcus Reed",
      time: "04:58 PM",
      text: "Rolling out of Austin now. Traffic looks clean on I-35.",
      reactions: [{ emoji: "👍", count: 2, mine: true }],
    },
    {
      id: "m2",
      kind: "location",
      from: "them",
      authorName: "Marcus Reed",
      time: "05:02 PM",
      label: "Live location",
      city: "Round Rock, TX",
      coords: "30.5083° N, 97.6789° W",
    },
    {
      id: "m3",
      kind: "text",
      from: "me",
      time: "05:05 PM",
      text: "Got you on the map. Dock 4 will be open when you arrive.",
    },
    {
      id: "m4",
      kind: "voice",
      from: "them",
      authorName: "Marcus Reed",
      time: "05:09 PM",
      durationSec: 14,
      waveform: [3, 6, 10, 14, 9, 12, 16, 8, 11, 14, 6, 9, 12, 7, 4, 10, 13, 8],
    },
    {
      id: "m5",
      kind: "load_status",
      from: "them",
      time: "05:14 PM",
      loadId: "LD-1048",
      status: "ETA updated",
      eta: "42 min",
      note: "Auto-update from in-trip navigation",
    },
    {
      id: "m6",
      kind: "text",
      from: "them",
      authorName: "Marcus Reed",
      time: "05:18 PM",
      text: "I'm 12 minutes from dropoff.",
      threadCount: 2,
      priority: "important",
    },
  ],
  harrold: [
    {
      id: "h1",
      kind: "text",
      from: "them",
      authorName: "Harrold Tafoya",
      time: "04:44 PM",
      text: "Hey — can you send the updated BOL for LD-1048?",
    },
    {
      id: "h2",
      kind: "text",
      from: "me",
      time: "04:46 PM",
      text: "On it. Sending now.",
      quote: { name: "Harrold Tafoya", text: "send the updated BOL" },
    },
    {
      id: "h3",
      kind: "file",
      from: "me",
      time: "04:47 PM",
      filename: "BOL_LD-1048_v2.pdf",
      filetype: "PDF",
      sizeKb: 248,
    },
    {
      id: "h4",
      kind: "text",
      from: "them",
      authorName: "Harrold Tafoya",
      time: "05:11 PM",
      text: "Perfect, thanks. Will forward to receiving.",
      reactions: [
        { emoji: "🙌", count: 1, mine: true },
        { emoji: "✅", count: 1 },
      ],
    },
  ],
  "ch-dispatch": [
    {
      id: "c1",
      kind: "system",
      from: "them",
      time: "—",
      text: "Channel created · 12 members",
      icon: "info",
    },
    {
      id: "c2",
      kind: "text",
      from: "them",
      authorName: "Dispatch Bot",
      time: "05:30 PM",
      text: "⚠️ Weather advisory: heavy rain on I-35 between Waco and Hillsboro.",
      priority: "urgent",
    },
    {
      id: "c3",
      kind: "text",
      from: "me",
      time: "05:32 PM",
      text: "Re-routing LD-1048 and LD-1052 via US-77. @marcus please confirm.",
      mentions: ["marcus"],
      reactions: [{ emoji: "👀", count: 3 }],
      threadCount: 4,
    },
    {
      id: "c4",
      kind: "load_status",
      from: "them",
      time: "05:34 PM",
      loadId: "LD-1052",
      status: "Re-routed",
      eta: "+18 min",
      note: "Auto-applied via dispatch rule",
    },
  ],
  "load-ld1048": [
    {
      id: "l1",
      kind: "system",
      from: "them",
      time: "—",
      text: "Load chat opened · Marcus Reed, Harrold Tafoya, Dallas DC Dock 4",
      icon: "info",
    },
    {
      id: "l2",
      kind: "load_status",
      from: "them",
      time: "02:14 PM",
      loadId: "LD-1048",
      status: "Picked up",
      note: "Origin: Austin DC",
    },
    {
      id: "l3",
      kind: "text",
      from: "them",
      authorName: "Marcus Reed",
      time: "05:18 PM",
      text: "12 min out.",
    },
  ],
  sarah: [
    {
      id: "s1",
      kind: "text",
      from: "them",
      authorName: "Sarah Milton",
      time: "04:40 PM",
      text: "Hi — would it be possible to push delivery to tomorrow morning?",
    },
    {
      id: "s2",
      kind: "text",
      from: "me",
      time: "04:47 PM",
      text: "Checking with the carrier now — back to you in 5.",
    },
  ],
};
