import type { Contact, Message } from "./types";

export const seedContacts: Contact[] = [
  {
    id: "harrold",
    name: "Harrold Tafoya",
    role: "Carrier",
    preview: "Typing…",
    time: "05:11 PM",
    unread: 0,
    pinned: true,
    typing: true,
    company: "PSP Cargo Group",
    avatar: "https://i.pravatar.cc/80?img=12",
    category: "pinned",
  },
  {
    id: "mate",
    name: "Mate Bruney",
    role: "Carrier",
    preview: "Thank you. Glad to feel this …",
    time: "04:17 PM",
    unread: 4,
    avatar: "https://i.pravatar.cc/80?img=13",
    category: "active_loads",
  },
  {
    id: "shannon",
    name: "Shannon Kile",
    role: "Driver",
    preview: "Yes, thank you…",
    time: "16:01 PM",
    unread: 2,
    avatar: "https://i.pravatar.cc/80?img=47",
    category: "active_loads",
  },
  {
    id: "kynie",
    name: "Kynie Mccotter",
    role: "Carrier",
    preview: "Have you had a chance to check it out?",
    time: "03:29 PM",
    unread: 3,
    avatar: "https://i.pravatar.cc/80?img=14",
    category: "dispatch",
  },
  {
    id: "savina",
    name: "Savina Navarrate",
    role: "Carrier",
    preview: "I'm already at the warehouse and…",
    time: "02:11 PM",
    unread: 1,
    avatar: "https://i.pravatar.cc/80?img=45",
    category: "dispatch",
  },
  {
    id: "marcel",
    name: "Marcel Pasculli",
    role: "Driver",
    preview: "Could you send me an updated invoice?",
    time: "Yesterday",
    unread: 0,
    avatar: "https://i.pravatar.cc/80?img=15",
    category: "invoices",
  },
  {
    id: "gilbertine",
    name: "Gilbertine Rivet",
    role: "Driver",
    preview: "Yes, I am. I will let you know…",
    time: "Yesterday",
    unread: 0,
    avatar: "https://i.pravatar.cc/80?img=33",
    category: "dispatch",
  },
  {
    id: "nisa",
    name: "Nisa Cordial",
    role: "Driver",
    preview: "Yes, thank you…",
    time: "Yesterday",
    unread: 0,
    avatar: "https://i.pravatar.cc/80?img=44",
    category: "completed",
  },
  {
    id: "rafi",
    name: "Rafi Rohamat",
    role: "Carrier",
    preview: "I'm already at the warehouse and…",
    time: "Dec 20, 2024",
    unread: 0,
    avatar: "https://i.pravatar.cc/80?img=16",
    category: "completed",
  },
  {
    id: "wenston",
    name: "Wenston Covil",
    role: "Driver",
    preview: "Can I fill up here? Location",
    time: "Dec 18, 2024",
    unread: 0,
    avatar: "https://i.pravatar.cc/80?img=17",
    category: "completed",
  },
  {
    id: "warehouse-atl",
    name: "ATL Hub Receiving",
    role: "Warehouse",
    company: "Anderoute Atlanta Hub",
    preview: "Dock 4 open at 14:00.",
    time: "Yesterday",
    unread: 0,
    avatar: "https://i.pravatar.cc/80?img=58",
    category: "dispatch",
  },
  {
    id: "broker-jane",
    name: "Jane Whitlow",
    role: "Broker",
    company: "Whitlow Logistics",
    preview: "Confirmed rate on lane.",
    time: "Yesterday",
    unread: 0,
    avatar: "https://i.pravatar.cc/80?img=49",
    category: "active_loads",
  },
];

export const seedMessages: Record<string, Message[]> = {
  harrold: [
    {
      id: "m1",
      kind: "text",
      from: "me",
      time: "09:44 PM",
      text: "Sounds perfect. I will drop a message to Nick regarding changes.",
    },
    {
      id: "m2",
      kind: "text",
      from: "me",
      time: "09:45 PM",
      text: "I'm afraid, yes, he will 🙂",
      quote: { name: "Mate Bruney", text: "Wa he insist on this date?" },
    },
    {
      id: "m3",
      kind: "text",
      from: "them",
      time: "09:44 PM",
      text:
        "Nick, payday is coming. Can you copy the invoice for our bookkeeping department?",
    },
    {
      id: "m4",
      kind: "text",
      from: "me",
      time: "10:50 PM",
      text:
        "I'm attaching the invoice for the last shipment. Please check it out and assure of correctness.",
    },
    {
      id: "m5",
      kind: "file",
      from: "me",
      time: "10:51 PM",
      filename: "Invoice Ceva Bahn 21032023",
      filetype: "PDF",
    },
    {
      id: "m6",
      kind: "text",
      from: "them",
      time: "09:44 PM",
      text: "Thank you! Glad to feel this difference",
    },
  ],
};
