/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoadsRouteImport } from './routes/loads'
import { Route as FuelRouteImport } from './routes/fuel'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminChangePasswordRouteImport } from './routes/admin-change-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as SettingsWhiteLabelRouteImport } from './routes/settings.white-label'
import { Route as SettingsProductionMonitoringRouteImport } from './routes/settings.production-monitoring'
import { Route as SettingsProductionRouteImport } from './routes/settings.production'
import { Route as SettingsEmailTemplatesRouteImport } from './routes/settings.email-templates'
import { Route as SettingsBillingRouteImport } from './routes/settings.billing'
import { Route as RatingQuoteRouteImport } from './routes/rating.quote'
import { Route as PortalNewRequestRouteImport } from './routes/portal.new-request'
import { Route as OptimizationCenterRouteImport } from './routes/optimization.center'
import { Route as IntegrationsWebhooksRouteImport } from './routes/integrations.webhooks'
import { Route as IntegrationsHubRouteImport } from './routes/integrations.hub'
import { Route as IntegrationsHealthRouteImport } from './routes/integrations.health'
import { Route as IntegrationsEdiRouteImport } from './routes/integrations.edi'
import { Route as IntegrationsApiRouteImport } from './routes/integrations.api'
import { Route as EnterprisePhase7DemoRouteImport } from './routes/enterprise.phase7-demo'
import { Route as EnterpriseOverviewRouteImport } from './routes/enterprise.overview'
import { Route as DriverPhase5DemoRouteImport } from './routes/driver.phase5-demo'
import { Route as DriverNotificationsLabRouteImport } from './routes/driver.notifications-lab'
import { Route as DriverNavigationRouteImport } from './routes/driver.navigation'
import { Route as DriverNavLabRouteImport } from './routes/driver.nav-lab'
import { Route as DriverElitenavRouteImport } from './routes/driver.elitenav'
import { Route as DriverEliteNavRouteImport } from './routes/driver.elite-nav'
import { Route as DriverDeliveriesRouteImport } from './routes/driver.deliveries'
import { Route as DriverCopilotLabRouteImport } from './routes/driver.copilot-lab'
import { Route as DispatchCommandCenterRouteImport } from './routes/dispatch.command-center'
import { Route as DataImportExportRouteImport } from './routes/data.import-export'
import { Route as AdminPlatformRouteImport } from './routes/admin.platform'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadsRoute = LoadsRouteImport.update({
  id: '/loads',
  path: '/loads',
  getParentRoute: () => rootRouteImport,
} as any)
const FuelRoute = FuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChangePasswordRoute = AdminChangePasswordRouteImport.update({
  id: '/admin-change-password',
  path: '/admin-change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/driver/',
  path: '/driver/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWhiteLabelRoute = SettingsWhiteLabelRouteImport.update({
  id: '/white-label',
  path: '/white-label',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProductionMonitoringRoute =
  SettingsProductionMonitoringRouteImport.update({
    id: '/production-monitoring',
    path: '/production-monitoring',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsProductionRoute = SettingsProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsEmailTemplatesRoute = SettingsEmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRoute,
} as any)
const RatingQuoteRoute = RatingQuoteRouteImport.update({
  id: '/rating/quote',
  path: '/rating/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalNewRequestRoute = PortalNewRequestRouteImport.update({
  id: '/new-request',
  path: '/new-request',
  getParentRoute: () => PortalRoute,
} as any)
const OptimizationCenterRoute = OptimizationCenterRouteImport.update({
  id: '/optimization/center',
  path: '/optimization/center',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsWebhooksRoute = IntegrationsWebhooksRouteImport.update({
  id: '/integrations/webhooks',
  path: '/integrations/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsHubRoute = IntegrationsHubRouteImport.update({
  id: '/integrations/hub',
  path: '/integrations/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsHealthRoute = IntegrationsHealthRouteImport.update({
  id: '/integrations/health',
  path: '/integrations/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsEdiRoute = IntegrationsEdiRouteImport.update({
  id: '/integrations/edi',
  path: '/integrations/edi',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsApiRoute = IntegrationsApiRouteImport.update({
  id: '/integrations/api',
  path: '/integrations/api',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterprisePhase7DemoRoute = EnterprisePhase7DemoRouteImport.update({
  id: '/enterprise/phase7-demo',
  path: '/enterprise/phase7-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseOverviewRoute = EnterpriseOverviewRouteImport.update({
  id: '/enterprise/overview',
  path: '/enterprise/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverPhase5DemoRoute = DriverPhase5DemoRouteImport.update({
  id: '/driver/phase5-demo',
  path: '/driver/phase5-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverNotificationsLabRoute = DriverNotificationsLabRouteImport.update({
  id: '/driver/notifications-lab',
  path: '/driver/notifications-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverNavigationRoute = DriverNavigationRouteImport.update({
  id: '/driver/navigation',
  path: '/driver/navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverNavLabRoute = DriverNavLabRouteImport.update({
  id: '/driver/nav-lab',
  path: '/driver/nav-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverElitenavRoute = DriverElitenavRouteImport.update({
  id: '/driver/elitenav',
  path: '/driver/elitenav',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverEliteNavRoute = DriverEliteNavRouteImport.update({
  id: '/driver/elite-nav',
  path: '/driver/elite-nav',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverDeliveriesRoute = DriverDeliveriesRouteImport.update({
  id: '/driver/deliveries',
  path: '/driver/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverCopilotLabRoute = DriverCopilotLabRouteImport.update({
  id: '/driver/copilot-lab',
  path: '/driver/copilot-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchCommandCenterRoute = DispatchCommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => DispatchRoute,
} as any)
const DataImportExportRoute = DataImportExportRouteImport.update({
  id: '/data/import-export',
  path: '/data/import-export',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlatformRoute = AdminPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-change-password': typeof AdminChangePasswordRoute
  '/admin-login': typeof AdminLoginRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/dispatch': typeof DispatchRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/drivers': typeof DriversRoute
  '/fuel': typeof FuelRoute
  '/loads': typeof LoadsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/portal': typeof PortalRouteWithChildren
  '/routes': typeof RoutesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/shipments': typeof ShipmentsRoute
  '/signup': typeof SignupRoute
  '/vehicles': typeof VehiclesRoute
  '/admin/platform': typeof AdminPlatformRoute
  '/data/import-export': typeof DataImportExportRoute
  '/dispatch/command-center': typeof DispatchCommandCenterRoute
  '/driver/copilot-lab': typeof DriverCopilotLabRoute
  '/driver/deliveries': typeof DriverDeliveriesRoute
  '/driver/elite-nav': typeof DriverEliteNavRoute
  '/driver/elitenav': typeof DriverElitenavRoute
  '/driver/nav-lab': typeof DriverNavLabRoute
  '/driver/navigation': typeof DriverNavigationRoute
  '/driver/notifications-lab': typeof DriverNotificationsLabRoute
  '/driver/phase5-demo': typeof DriverPhase5DemoRoute
  '/enterprise/overview': typeof EnterpriseOverviewRoute
  '/enterprise/phase7-demo': typeof EnterprisePhase7DemoRoute
  '/integrations/api': typeof IntegrationsApiRoute
  '/integrations/edi': typeof IntegrationsEdiRoute
  '/integrations/health': typeof IntegrationsHealthRoute
  '/integrations/hub': typeof IntegrationsHubRoute
  '/integrations/webhooks': typeof IntegrationsWebhooksRoute
  '/optimization/center': typeof OptimizationCenterRoute
  '/portal/new-request': typeof PortalNewRequestRoute
  '/rating/quote': typeof RatingQuoteRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/email-templates': typeof SettingsEmailTemplatesRoute
  '/settings/production': typeof SettingsProductionRoute
  '/settings/production-monitoring': typeof SettingsProductionMonitoringRoute
  '/settings/white-label': typeof SettingsWhiteLabelRoute
  '/driver/': typeof DriverIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-change-password': typeof AdminChangePasswordRoute
  '/admin-login': typeof AdminLoginRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/dispatch': typeof DispatchRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/drivers': typeof DriversRoute
  '/fuel': typeof FuelRoute
  '/loads': typeof LoadsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/portal': typeof PortalRouteWithChildren
  '/routes': typeof RoutesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/shipments': typeof ShipmentsRoute
  '/signup': typeof SignupRoute
  '/vehicles': typeof VehiclesRoute
  '/admin/platform': typeof AdminPlatformRoute
  '/data/import-export': typeof DataImportExportRoute
  '/dispatch/command-center': typeof DispatchCommandCenterRoute
  '/driver/copilot-lab': typeof DriverCopilotLabRoute
  '/driver/deliveries': typeof DriverDeliveriesRoute
  '/driver/elite-nav': typeof DriverEliteNavRoute
  '/driver/elitenav': typeof DriverElitenavRoute
  '/driver/nav-lab': typeof DriverNavLabRoute
  '/driver/navigation': typeof DriverNavigationRoute
  '/driver/notifications-lab': typeof DriverNotificationsLabRoute
  '/driver/phase5-demo': typeof DriverPhase5DemoRoute
  '/enterprise/overview': typeof EnterpriseOverviewRoute
  '/enterprise/phase7-demo': typeof EnterprisePhase7DemoRoute
  '/integrations/api': typeof IntegrationsApiRoute
  '/integrations/edi': typeof IntegrationsEdiRoute
  '/integrations/health': typeof IntegrationsHealthRoute
  '/integrations/hub': typeof IntegrationsHubRoute
  '/integrations/webhooks': typeof IntegrationsWebhooksRoute
  '/optimization/center': typeof OptimizationCenterRoute
  '/portal/new-request': typeof PortalNewRequestRoute
  '/rating/quote': typeof RatingQuoteRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/email-templates': typeof SettingsEmailTemplatesRoute
  '/settings/production': typeof SettingsProductionRoute
  '/settings/production-monitoring': typeof SettingsProductionMonitoringRoute
  '/settings/white-label': typeof SettingsWhiteLabelRoute
  '/driver': typeof DriverIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-change-password': typeof AdminChangePasswordRoute
  '/admin-login': typeof AdminLoginRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/dispatch': typeof DispatchRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/drivers': typeof DriversRoute
  '/fuel': typeof FuelRoute
  '/loads': typeof LoadsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/portal': typeof PortalRouteWithChildren
  '/routes': typeof RoutesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/shipments': typeof ShipmentsRoute
  '/signup': typeof SignupRoute
  '/vehicles': typeof VehiclesRoute
  '/admin/platform': typeof AdminPlatformRoute
  '/data/import-export': typeof DataImportExportRoute
  '/dispatch/command-center': typeof DispatchCommandCenterRoute
  '/driver/copilot-lab': typeof DriverCopilotLabRoute
  '/driver/deliveries': typeof DriverDeliveriesRoute
  '/driver/elite-nav': typeof DriverEliteNavRoute
  '/driver/elitenav': typeof DriverElitenavRoute
  '/driver/nav-lab': typeof DriverNavLabRoute
  '/driver/navigation': typeof DriverNavigationRoute
  '/driver/notifications-lab': typeof DriverNotificationsLabRoute
  '/driver/phase5-demo': typeof DriverPhase5DemoRoute
  '/enterprise/overview': typeof EnterpriseOverviewRoute
  '/enterprise/phase7-demo': typeof EnterprisePhase7DemoRoute
  '/integrations/api': typeof IntegrationsApiRoute
  '/integrations/edi': typeof IntegrationsEdiRoute
  '/integrations/health': typeof IntegrationsHealthRoute
  '/integrations/hub': typeof IntegrationsHubRoute
  '/integrations/webhooks': typeof IntegrationsWebhooksRoute
  '/optimization/center': typeof OptimizationCenterRoute
  '/portal/new-request': typeof PortalNewRequestRoute
  '/rating/quote': typeof RatingQuoteRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/email-templates': typeof SettingsEmailTemplatesRoute
  '/settings/production': typeof SettingsProductionRoute
  '/settings/production-monitoring': typeof SettingsProductionMonitoringRoute
  '/settings/white-label': typeof SettingsWhiteLabelRoute
  '/driver/': typeof DriverIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-change-password'
    | '/admin-login'
    | '/alerts'
    | '/analytics'
    | '/dispatch'
    | '/documents'
    | '/drivers'
    | '/fuel'
    | '/loads'
    | '/login'
    | '/map'
    | '/portal'
    | '/routes'
    | '/settings'
    | '/shipments'
    | '/signup'
    | '/vehicles'
    | '/admin/platform'
    | '/data/import-export'
    | '/dispatch/command-center'
    | '/driver/copilot-lab'
    | '/driver/deliveries'
    | '/driver/elite-nav'
    | '/driver/elitenav'
    | '/driver/nav-lab'
    | '/driver/navigation'
    | '/driver/notifications-lab'
    | '/driver/phase5-demo'
    | '/enterprise/overview'
    | '/enterprise/phase7-demo'
    | '/integrations/api'
    | '/integrations/edi'
    | '/integrations/health'
    | '/integrations/hub'
    | '/integrations/webhooks'
    | '/optimization/center'
    | '/portal/new-request'
    | '/rating/quote'
    | '/settings/billing'
    | '/settings/email-templates'
    | '/settings/production'
    | '/settings/production-monitoring'
    | '/settings/white-label'
    | '/driver/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-change-password'
    | '/admin-login'
    | '/alerts'
    | '/analytics'
    | '/dispatch'
    | '/documents'
    | '/drivers'
    | '/fuel'
    | '/loads'
    | '/login'
    | '/map'
    | '/portal'
    | '/routes'
    | '/settings'
    | '/shipments'
    | '/signup'
    | '/vehicles'
    | '/admin/platform'
    | '/data/import-export'
    | '/dispatch/command-center'
    | '/driver/copilot-lab'
    | '/driver/deliveries'
    | '/driver/elite-nav'
    | '/driver/elitenav'
    | '/driver/nav-lab'
    | '/driver/navigation'
    | '/driver/notifications-lab'
    | '/driver/phase5-demo'
    | '/enterprise/overview'
    | '/enterprise/phase7-demo'
    | '/integrations/api'
    | '/integrations/edi'
    | '/integrations/health'
    | '/integrations/hub'
    | '/integrations/webhooks'
    | '/optimization/center'
    | '/portal/new-request'
    | '/rating/quote'
    | '/settings/billing'
    | '/settings/email-templates'
    | '/settings/production'
    | '/settings/production-monitoring'
    | '/settings/white-label'
    | '/driver'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-change-password'
    | '/admin-login'
    | '/alerts'
    | '/analytics'
    | '/dispatch'
    | '/documents'
    | '/drivers'
    | '/fuel'
    | '/loads'
    | '/login'
    | '/map'
    | '/portal'
    | '/routes'
    | '/settings'
    | '/shipments'
    | '/signup'
    | '/vehicles'
    | '/admin/platform'
    | '/data/import-export'
    | '/dispatch/command-center'
    | '/driver/copilot-lab'
    | '/driver/deliveries'
    | '/driver/elite-nav'
    | '/driver/elitenav'
    | '/driver/nav-lab'
    | '/driver/navigation'
    | '/driver/notifications-lab'
    | '/driver/phase5-demo'
    | '/enterprise/overview'
    | '/enterprise/phase7-demo'
    | '/integrations/api'
    | '/integrations/edi'
    | '/integrations/health'
    | '/integrations/hub'
    | '/integrations/webhooks'
    | '/optimization/center'
    | '/portal/new-request'
    | '/rating/quote'
    | '/settings/billing'
    | '/settings/email-templates'
    | '/settings/production'
    | '/settings/production-monitoring'
    | '/settings/white-label'
    | '/driver/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminChangePasswordRoute: typeof AdminChangePasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DispatchRoute: typeof DispatchRouteWithChildren
  DocumentsRoute: typeof DocumentsRoute
  DriversRoute: typeof DriversRoute
  FuelRoute: typeof FuelRoute
  LoadsRoute: typeof LoadsRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  PortalRoute: typeof PortalRouteWithChildren
  RoutesRoute: typeof RoutesRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ShipmentsRoute: typeof ShipmentsRoute
  SignupRoute: typeof SignupRoute
  VehiclesRoute: typeof VehiclesRoute
  DataImportExportRoute: typeof DataImportExportRoute
  DriverCopilotLabRoute: typeof DriverCopilotLabRoute
  DriverDeliveriesRoute: typeof DriverDeliveriesRoute
  DriverEliteNavRoute: typeof DriverEliteNavRoute
  DriverElitenavRoute: typeof DriverElitenavRoute
  DriverNavLabRoute: typeof DriverNavLabRoute
  DriverNavigationRoute: typeof DriverNavigationRoute
  DriverNotificationsLabRoute: typeof DriverNotificationsLabRoute
  DriverPhase5DemoRoute: typeof DriverPhase5DemoRoute
  EnterpriseOverviewRoute: typeof EnterpriseOverviewRoute
  EnterprisePhase7DemoRoute: typeof EnterprisePhase7DemoRoute
  IntegrationsApiRoute: typeof IntegrationsApiRoute
  IntegrationsEdiRoute: typeof IntegrationsEdiRoute
  IntegrationsHealthRoute: typeof IntegrationsHealthRoute
  IntegrationsHubRoute: typeof IntegrationsHubRoute
  IntegrationsWebhooksRoute: typeof IntegrationsWebhooksRoute
  OptimizationCenterRoute: typeof OptimizationCenterRoute
  RatingQuoteRoute: typeof RatingQuoteRoute
  DriverIndexRoute: typeof DriverIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loads': {
      id: '/loads'
      path: '/loads'
      fullPath: '/loads'
      preLoaderRoute: typeof LoadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuel': {
      id: '/fuel'
      path: '/fuel'
      fullPath: '/fuel'
      preLoaderRoute: typeof FuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-change-password': {
      id: '/admin-change-password'
      path: '/admin-change-password'
      fullPath: '/admin-change-password'
      preLoaderRoute: typeof AdminChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/driver'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/white-label': {
      id: '/settings/white-label'
      path: '/white-label'
      fullPath: '/settings/white-label'
      preLoaderRoute: typeof SettingsWhiteLabelRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/production-monitoring': {
      id: '/settings/production-monitoring'
      path: '/production-monitoring'
      fullPath: '/settings/production-monitoring'
      preLoaderRoute: typeof SettingsProductionMonitoringRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/production': {
      id: '/settings/production'
      path: '/production'
      fullPath: '/settings/production'
      preLoaderRoute: typeof SettingsProductionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/email-templates': {
      id: '/settings/email-templates'
      path: '/email-templates'
      fullPath: '/settings/email-templates'
      preLoaderRoute: typeof SettingsEmailTemplatesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/rating/quote': {
      id: '/rating/quote'
      path: '/rating/quote'
      fullPath: '/rating/quote'
      preLoaderRoute: typeof RatingQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/new-request': {
      id: '/portal/new-request'
      path: '/new-request'
      fullPath: '/portal/new-request'
      preLoaderRoute: typeof PortalNewRequestRouteImport
      parentRoute: typeof PortalRoute
    }
    '/optimization/center': {
      id: '/optimization/center'
      path: '/optimization/center'
      fullPath: '/optimization/center'
      preLoaderRoute: typeof OptimizationCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/webhooks': {
      id: '/integrations/webhooks'
      path: '/integrations/webhooks'
      fullPath: '/integrations/webhooks'
      preLoaderRoute: typeof IntegrationsWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/hub': {
      id: '/integrations/hub'
      path: '/integrations/hub'
      fullPath: '/integrations/hub'
      preLoaderRoute: typeof IntegrationsHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/health': {
      id: '/integrations/health'
      path: '/integrations/health'
      fullPath: '/integrations/health'
      preLoaderRoute: typeof IntegrationsHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/edi': {
      id: '/integrations/edi'
      path: '/integrations/edi'
      fullPath: '/integrations/edi'
      preLoaderRoute: typeof IntegrationsEdiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/api': {
      id: '/integrations/api'
      path: '/integrations/api'
      fullPath: '/integrations/api'
      preLoaderRoute: typeof IntegrationsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise/phase7-demo': {
      id: '/enterprise/phase7-demo'
      path: '/enterprise/phase7-demo'
      fullPath: '/enterprise/phase7-demo'
      preLoaderRoute: typeof EnterprisePhase7DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise/overview': {
      id: '/enterprise/overview'
      path: '/enterprise/overview'
      fullPath: '/enterprise/overview'
      preLoaderRoute: typeof EnterpriseOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/phase5-demo': {
      id: '/driver/phase5-demo'
      path: '/driver/phase5-demo'
      fullPath: '/driver/phase5-demo'
      preLoaderRoute: typeof DriverPhase5DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/notifications-lab': {
      id: '/driver/notifications-lab'
      path: '/driver/notifications-lab'
      fullPath: '/driver/notifications-lab'
      preLoaderRoute: typeof DriverNotificationsLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/navigation': {
      id: '/driver/navigation'
      path: '/driver/navigation'
      fullPath: '/driver/navigation'
      preLoaderRoute: typeof DriverNavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/nav-lab': {
      id: '/driver/nav-lab'
      path: '/driver/nav-lab'
      fullPath: '/driver/nav-lab'
      preLoaderRoute: typeof DriverNavLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/elitenav': {
      id: '/driver/elitenav'
      path: '/driver/elitenav'
      fullPath: '/driver/elitenav'
      preLoaderRoute: typeof DriverElitenavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/elite-nav': {
      id: '/driver/elite-nav'
      path: '/driver/elite-nav'
      fullPath: '/driver/elite-nav'
      preLoaderRoute: typeof DriverEliteNavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/deliveries': {
      id: '/driver/deliveries'
      path: '/driver/deliveries'
      fullPath: '/driver/deliveries'
      preLoaderRoute: typeof DriverDeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/copilot-lab': {
      id: '/driver/copilot-lab'
      path: '/driver/copilot-lab'
      fullPath: '/driver/copilot-lab'
      preLoaderRoute: typeof DriverCopilotLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch/command-center': {
      id: '/dispatch/command-center'
      path: '/command-center'
      fullPath: '/dispatch/command-center'
      preLoaderRoute: typeof DispatchCommandCenterRouteImport
      parentRoute: typeof DispatchRoute
    }
    '/data/import-export': {
      id: '/data/import-export'
      path: '/data/import-export'
      fullPath: '/data/import-export'
      preLoaderRoute: typeof DataImportExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/platform': {
      id: '/admin/platform'
      path: '/platform'
      fullPath: '/admin/platform'
      preLoaderRoute: typeof AdminPlatformRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminPlatformRoute: typeof AdminPlatformRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPlatformRoute: AdminPlatformRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DispatchRouteChildren {
  DispatchCommandCenterRoute: typeof DispatchCommandCenterRoute
}

const DispatchRouteChildren: DispatchRouteChildren = {
  DispatchCommandCenterRoute: DispatchCommandCenterRoute,
}

const DispatchRouteWithChildren = DispatchRoute._addFileChildren(
  DispatchRouteChildren,
)

interface PortalRouteChildren {
  PortalNewRequestRoute: typeof PortalNewRequestRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalNewRequestRoute: PortalNewRequestRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface SettingsRouteChildren {
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsEmailTemplatesRoute: typeof SettingsEmailTemplatesRoute
  SettingsProductionRoute: typeof SettingsProductionRoute
  SettingsProductionMonitoringRoute: typeof SettingsProductionMonitoringRoute
  SettingsWhiteLabelRoute: typeof SettingsWhiteLabelRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsEmailTemplatesRoute: SettingsEmailTemplatesRoute,
  SettingsProductionRoute: SettingsProductionRoute,
  SettingsProductionMonitoringRoute: SettingsProductionMonitoringRoute,
  SettingsWhiteLabelRoute: SettingsWhiteLabelRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminChangePasswordRoute: AdminChangePasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  DispatchRoute: DispatchRouteWithChildren,
  DocumentsRoute: DocumentsRoute,
  DriversRoute: DriversRoute,
  FuelRoute: FuelRoute,
  LoadsRoute: LoadsRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  PortalRoute: PortalRouteWithChildren,
  RoutesRoute: RoutesRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ShipmentsRoute: ShipmentsRoute,
  SignupRoute: SignupRoute,
  VehiclesRoute: VehiclesRoute,
  DataImportExportRoute: DataImportExportRoute,
  DriverCopilotLabRoute: DriverCopilotLabRoute,
  DriverDeliveriesRoute: DriverDeliveriesRoute,
  DriverEliteNavRoute: DriverEliteNavRoute,
  DriverElitenavRoute: DriverElitenavRoute,
  DriverNavLabRoute: DriverNavLabRoute,
  DriverNavigationRoute: DriverNavigationRoute,
  DriverNotificationsLabRoute: DriverNotificationsLabRoute,
  DriverPhase5DemoRoute: DriverPhase5DemoRoute,
  EnterpriseOverviewRoute: EnterpriseOverviewRoute,
  EnterprisePhase7DemoRoute: EnterprisePhase7DemoRoute,
  IntegrationsApiRoute: IntegrationsApiRoute,
  IntegrationsEdiRoute: IntegrationsEdiRoute,
  IntegrationsHealthRoute: IntegrationsHealthRoute,
  IntegrationsHubRoute: IntegrationsHubRoute,
  IntegrationsWebhooksRoute: IntegrationsWebhooksRoute,
  OptimizationCenterRoute: OptimizationCenterRoute,
  RatingQuoteRoute: RatingQuoteRoute,
  DriverIndexRoute: DriverIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
