/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoadsRouteImport } from './routes/loads'
import { Route as FuelRouteImport } from './routes/fuel'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminChangePasswordRouteImport } from './routes/admin-change-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as SettingsWhiteLabelRouteImport } from './routes/settings.white-label'
import { Route as SettingsProductionMonitoringRouteImport } from './routes/settings.production-monitoring'
import { Route as SettingsProductionRouteImport } from './routes/settings.production'
import { Route as SettingsEmailTemplatesRouteImport } from './routes/settings.email-templates'
import { Route as SettingsBillingRouteImport } from './routes/settings.billing'
import { Route as SecurityPrivacyRouteImport } from './routes/security.privacy'
import { Route as SecurityPhase8OverviewRouteImport } from './routes/security.phase8-overview'
import { Route as SecurityOverviewRouteImport } from './routes/security.overview'
import { Route as SecurityCenterRouteImport } from './routes/security.center'
import { Route as RatingQuoteRouteImport } from './routes/rating.quote'
import { Route as PortalNewRequestRouteImport } from './routes/portal.new-request'
import { Route as OptimizationCenterRouteImport } from './routes/optimization.center'
import { Route as OpsObservabilityRouteImport } from './routes/ops.observability'
import { Route as OpsIncidentsRouteImport } from './routes/ops.incidents'
import { Route as OpsDatabaseRouteImport } from './routes/ops.database'
import { Route as OpsCenterRouteImport } from './routes/ops.center'
import { Route as LaunchSalesRouteImport } from './routes/launch.sales'
import { Route as LaunchRoiRouteImport } from './routes/launch.roi'
import { Route as LaunchPricingRouteImport } from './routes/launch.pricing'
import { Route as LaunchPilotRouteImport } from './routes/launch.pilot'
import { Route as LaunchOverviewRouteImport } from './routes/launch.overview'
import { Route as LaunchOnboardingRouteImport } from './routes/launch.onboarding'
import { Route as LaunchMarketingRouteImport } from './routes/launch.marketing'
import { Route as LaunchDocumentationRouteImport } from './routes/launch.documentation'
import { Route as LaunchDemoRouteImport } from './routes/launch.demo'
import { Route as IntelligenceRiskRouteImport } from './routes/intelligence.risk'
import { Route as IntelligenceRecommendationsRouteImport } from './routes/intelligence.recommendations'
import { Route as IntelligencePhase9OverviewRouteImport } from './routes/intelligence.phase9-overview'
import { Route as IntelligenceOverviewRouteImport } from './routes/intelligence.overview'
import { Route as IntelligenceHandoffRouteImport } from './routes/intelligence.handoff'
import { Route as IntelligenceGovernanceRouteImport } from './routes/intelligence.governance'
import { Route as IntelligenceExecutiveRouteImport } from './routes/intelligence.executive'
import { Route as IntelligenceEtaConfidenceRouteImport } from './routes/intelligence.eta-confidence'
import { Route as IntelligenceDispatchRouteImport } from './routes/intelligence.dispatch'
import { Route as IntelligenceCustomersRouteImport } from './routes/intelligence.customers'
import { Route as IntelligenceCapacityRouteImport } from './routes/intelligence.capacity'
import { Route as IntelligenceAlertsRouteImport } from './routes/intelligence.alerts'
import { Route as IntegrationsWebhooksRouteImport } from './routes/integrations.webhooks'
import { Route as IntegrationsHubRouteImport } from './routes/integrations.hub'
import { Route as IntegrationsHealthRouteImport } from './routes/integrations.health'
import { Route as IntegrationsEdiRouteImport } from './routes/integrations.edi'
import { Route as IntegrationsApiRouteImport } from './routes/integrations.api'
import { Route as EnterprisePhase7DemoRouteImport } from './routes/enterprise.phase7-demo'
import { Route as EnterpriseOverviewRouteImport } from './routes/enterprise.overview'
import { Route as DriverPhase5DemoRouteImport } from './routes/driver.phase5-demo'
import { Route as DriverNotificationsLabRouteImport } from './routes/driver.notifications-lab'
import { Route as DriverNavigationRouteImport } from './routes/driver.navigation'
import { Route as DriverNavLabRouteImport } from './routes/driver.nav-lab'
import { Route as DriverElitenavRouteImport } from './routes/driver.elitenav'
import { Route as DriverEliteNavRouteImport } from './routes/driver.elite-nav'
import { Route as DriverDeliveriesRouteImport } from './routes/driver.deliveries'
import { Route as DriverCopilotLabRouteImport } from './routes/driver.copilot-lab'
import { Route as DispatchCommandCenterRouteImport } from './routes/dispatch.command-center'
import { Route as DataImportExportRouteImport } from './routes/data.import-export'
import { Route as ComplianceSoc2RouteImport } from './routes/compliance.soc2'
import { Route as AdminPlatformRouteImport } from './routes/admin.platform'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadsRoute = LoadsRouteImport.update({
  id: '/loads',
  path: '/loads',
  getParentRoute: () => rootRouteImport,
} as any)
const FuelRoute = FuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChangePasswordRoute = AdminChangePasswordRouteImport.update({
  id: '/admin-change-password',
  path: '/admin-change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/driver/',
  path: '/driver/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWhiteLabelRoute = SettingsWhiteLabelRouteImport.update({
  id: '/white-label',
  path: '/white-label',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProductionMonitoringRoute =
  SettingsProductionMonitoringRouteImport.update({
    id: '/production-monitoring',
    path: '/production-monitoring',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsProductionRoute = SettingsProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsEmailTemplatesRoute = SettingsEmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRoute,
} as any)
const SecurityPrivacyRoute = SecurityPrivacyRouteImport.update({
  id: '/security/privacy',
  path: '/security/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityPhase8OverviewRoute = SecurityPhase8OverviewRouteImport.update({
  id: '/security/phase8-overview',
  path: '/security/phase8-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityOverviewRoute = SecurityOverviewRouteImport.update({
  id: '/security/overview',
  path: '/security/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityCenterRoute = SecurityCenterRouteImport.update({
  id: '/security/center',
  path: '/security/center',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingQuoteRoute = RatingQuoteRouteImport.update({
  id: '/rating/quote',
  path: '/rating/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalNewRequestRoute = PortalNewRequestRouteImport.update({
  id: '/new-request',
  path: '/new-request',
  getParentRoute: () => PortalRoute,
} as any)
const OptimizationCenterRoute = OptimizationCenterRouteImport.update({
  id: '/optimization/center',
  path: '/optimization/center',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsObservabilityRoute = OpsObservabilityRouteImport.update({
  id: '/ops/observability',
  path: '/ops/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsIncidentsRoute = OpsIncidentsRouteImport.update({
  id: '/ops/incidents',
  path: '/ops/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsDatabaseRoute = OpsDatabaseRouteImport.update({
  id: '/ops/database',
  path: '/ops/database',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsCenterRoute = OpsCenterRouteImport.update({
  id: '/ops/center',
  path: '/ops/center',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchSalesRoute = LaunchSalesRouteImport.update({
  id: '/launch/sales',
  path: '/launch/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoiRoute = LaunchRoiRouteImport.update({
  id: '/launch/roi',
  path: '/launch/roi',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchPricingRoute = LaunchPricingRouteImport.update({
  id: '/launch/pricing',
  path: '/launch/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchPilotRoute = LaunchPilotRouteImport.update({
  id: '/launch/pilot',
  path: '/launch/pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchOverviewRoute = LaunchOverviewRouteImport.update({
  id: '/launch/overview',
  path: '/launch/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchOnboardingRoute = LaunchOnboardingRouteImport.update({
  id: '/launch/onboarding',
  path: '/launch/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchMarketingRoute = LaunchMarketingRouteImport.update({
  id: '/launch/marketing',
  path: '/launch/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchDocumentationRoute = LaunchDocumentationRouteImport.update({
  id: '/launch/documentation',
  path: '/launch/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchDemoRoute = LaunchDemoRouteImport.update({
  id: '/launch/demo',
  path: '/launch/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRiskRoute = IntelligenceRiskRouteImport.update({
  id: '/intelligence/risk',
  path: '/intelligence/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRecommendationsRoute =
  IntelligenceRecommendationsRouteImport.update({
    id: '/intelligence/recommendations',
    path: '/intelligence/recommendations',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntelligencePhase9OverviewRoute =
  IntelligencePhase9OverviewRouteImport.update({
    id: '/intelligence/phase9-overview',
    path: '/intelligence/phase9-overview',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntelligenceOverviewRoute = IntelligenceOverviewRouteImport.update({
  id: '/intelligence/overview',
  path: '/intelligence/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceHandoffRoute = IntelligenceHandoffRouteImport.update({
  id: '/intelligence/handoff',
  path: '/intelligence/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceGovernanceRoute = IntelligenceGovernanceRouteImport.update({
  id: '/intelligence/governance',
  path: '/intelligence/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceExecutiveRoute = IntelligenceExecutiveRouteImport.update({
  id: '/intelligence/executive',
  path: '/intelligence/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceEtaConfidenceRoute =
  IntelligenceEtaConfidenceRouteImport.update({
    id: '/intelligence/eta-confidence',
    path: '/intelligence/eta-confidence',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntelligenceDispatchRoute = IntelligenceDispatchRouteImport.update({
  id: '/intelligence/dispatch',
  path: '/intelligence/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceCustomersRoute = IntelligenceCustomersRouteImport.update({
  id: '/intelligence/customers',
  path: '/intelligence/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceCapacityRoute = IntelligenceCapacityRouteImport.update({
  id: '/intelligence/capacity',
  path: '/intelligence/capacity',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceAlertsRoute = IntelligenceAlertsRouteImport.update({
  id: '/intelligence/alerts',
  path: '/intelligence/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsWebhooksRoute = IntegrationsWebhooksRouteImport.update({
  id: '/integrations/webhooks',
  path: '/integrations/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsHubRoute = IntegrationsHubRouteImport.update({
  id: '/integrations/hub',
  path: '/integrations/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsHealthRoute = IntegrationsHealthRouteImport.update({
  id: '/integrations/health',
  path: '/integrations/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsEdiRoute = IntegrationsEdiRouteImport.update({
  id: '/integrations/edi',
  path: '/integrations/edi',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsApiRoute = IntegrationsApiRouteImport.update({
  id: '/integrations/api',
  path: '/integrations/api',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterprisePhase7DemoRoute = EnterprisePhase7DemoRouteImport.update({
  id: '/enterprise/phase7-demo',
  path: '/enterprise/phase7-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseOverviewRoute = EnterpriseOverviewRouteImport.update({
  id: '/enterprise/overview',
  path: '/enterprise/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverPhase5DemoRoute = DriverPhase5DemoRouteImport.update({
  id: '/driver/phase5-demo',
  path: '/driver/phase5-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverNotificationsLabRoute = DriverNotificationsLabRouteImport.update({
  id: '/driver/notifications-lab',
  path: '/driver/notifications-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverNavigationRoute = DriverNavigationRouteImport.update({
  id: '/driver/navigation',
  path: '/driver/navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverNavLabRoute = DriverNavLabRouteImport.update({
  id: '/driver/nav-lab',
  path: '/driver/nav-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverElitenavRoute = DriverElitenavRouteImport.update({
  id: '/driver/elitenav',
  path: '/driver/elitenav',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverEliteNavRoute = DriverEliteNavRouteImport.update({
  id: '/driver/elite-nav',
  path: '/driver/elite-nav',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverDeliveriesRoute = DriverDeliveriesRouteImport.update({
  id: '/driver/deliveries',
  path: '/driver/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverCopilotLabRoute = DriverCopilotLabRouteImport.update({
  id: '/driver/copilot-lab',
  path: '/driver/copilot-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchCommandCenterRoute = DispatchCommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => DispatchRoute,
} as any)
const DataImportExportRoute = DataImportExportRouteImport.update({
  id: '/data/import-export',
  path: '/data/import-export',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceSoc2Route = ComplianceSoc2RouteImport.update({
  id: '/compliance/soc2',
  path: '/compliance/soc2',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlatformRoute = AdminPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-change-password': typeof AdminChangePasswordRoute
  '/admin-login': typeof AdminLoginRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/dispatch': typeof DispatchRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/drivers': typeof DriversRoute
  '/fuel': typeof FuelRoute
  '/loads': typeof LoadsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/portal': typeof PortalRouteWithChildren
  '/routes': typeof RoutesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/shipments': typeof ShipmentsRoute
  '/signup': typeof SignupRoute
  '/vehicles': typeof VehiclesRoute
  '/admin/platform': typeof AdminPlatformRoute
  '/compliance/soc2': typeof ComplianceSoc2Route
  '/data/import-export': typeof DataImportExportRoute
  '/dispatch/command-center': typeof DispatchCommandCenterRoute
  '/driver/copilot-lab': typeof DriverCopilotLabRoute
  '/driver/deliveries': typeof DriverDeliveriesRoute
  '/driver/elite-nav': typeof DriverEliteNavRoute
  '/driver/elitenav': typeof DriverElitenavRoute
  '/driver/nav-lab': typeof DriverNavLabRoute
  '/driver/navigation': typeof DriverNavigationRoute
  '/driver/notifications-lab': typeof DriverNotificationsLabRoute
  '/driver/phase5-demo': typeof DriverPhase5DemoRoute
  '/enterprise/overview': typeof EnterpriseOverviewRoute
  '/enterprise/phase7-demo': typeof EnterprisePhase7DemoRoute
  '/integrations/api': typeof IntegrationsApiRoute
  '/integrations/edi': typeof IntegrationsEdiRoute
  '/integrations/health': typeof IntegrationsHealthRoute
  '/integrations/hub': typeof IntegrationsHubRoute
  '/integrations/webhooks': typeof IntegrationsWebhooksRoute
  '/intelligence/alerts': typeof IntelligenceAlertsRoute
  '/intelligence/capacity': typeof IntelligenceCapacityRoute
  '/intelligence/customers': typeof IntelligenceCustomersRoute
  '/intelligence/dispatch': typeof IntelligenceDispatchRoute
  '/intelligence/eta-confidence': typeof IntelligenceEtaConfidenceRoute
  '/intelligence/executive': typeof IntelligenceExecutiveRoute
  '/intelligence/governance': typeof IntelligenceGovernanceRoute
  '/intelligence/handoff': typeof IntelligenceHandoffRoute
  '/intelligence/overview': typeof IntelligenceOverviewRoute
  '/intelligence/phase9-overview': typeof IntelligencePhase9OverviewRoute
  '/intelligence/recommendations': typeof IntelligenceRecommendationsRoute
  '/intelligence/risk': typeof IntelligenceRiskRoute
  '/launch/demo': typeof LaunchDemoRoute
  '/launch/documentation': typeof LaunchDocumentationRoute
  '/launch/marketing': typeof LaunchMarketingRoute
  '/launch/onboarding': typeof LaunchOnboardingRoute
  '/launch/overview': typeof LaunchOverviewRoute
  '/launch/pilot': typeof LaunchPilotRoute
  '/launch/pricing': typeof LaunchPricingRoute
  '/launch/roi': typeof LaunchRoiRoute
  '/launch/sales': typeof LaunchSalesRoute
  '/ops/center': typeof OpsCenterRoute
  '/ops/database': typeof OpsDatabaseRoute
  '/ops/incidents': typeof OpsIncidentsRoute
  '/ops/observability': typeof OpsObservabilityRoute
  '/optimization/center': typeof OptimizationCenterRoute
  '/portal/new-request': typeof PortalNewRequestRoute
  '/rating/quote': typeof RatingQuoteRoute
  '/security/center': typeof SecurityCenterRoute
  '/security/overview': typeof SecurityOverviewRoute
  '/security/phase8-overview': typeof SecurityPhase8OverviewRoute
  '/security/privacy': typeof SecurityPrivacyRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/email-templates': typeof SettingsEmailTemplatesRoute
  '/settings/production': typeof SettingsProductionRoute
  '/settings/production-monitoring': typeof SettingsProductionMonitoringRoute
  '/settings/white-label': typeof SettingsWhiteLabelRoute
  '/driver/': typeof DriverIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-change-password': typeof AdminChangePasswordRoute
  '/admin-login': typeof AdminLoginRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/dispatch': typeof DispatchRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/drivers': typeof DriversRoute
  '/fuel': typeof FuelRoute
  '/loads': typeof LoadsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/portal': typeof PortalRouteWithChildren
  '/routes': typeof RoutesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/shipments': typeof ShipmentsRoute
  '/signup': typeof SignupRoute
  '/vehicles': typeof VehiclesRoute
  '/admin/platform': typeof AdminPlatformRoute
  '/compliance/soc2': typeof ComplianceSoc2Route
  '/data/import-export': typeof DataImportExportRoute
  '/dispatch/command-center': typeof DispatchCommandCenterRoute
  '/driver/copilot-lab': typeof DriverCopilotLabRoute
  '/driver/deliveries': typeof DriverDeliveriesRoute
  '/driver/elite-nav': typeof DriverEliteNavRoute
  '/driver/elitenav': typeof DriverElitenavRoute
  '/driver/nav-lab': typeof DriverNavLabRoute
  '/driver/navigation': typeof DriverNavigationRoute
  '/driver/notifications-lab': typeof DriverNotificationsLabRoute
  '/driver/phase5-demo': typeof DriverPhase5DemoRoute
  '/enterprise/overview': typeof EnterpriseOverviewRoute
  '/enterprise/phase7-demo': typeof EnterprisePhase7DemoRoute
  '/integrations/api': typeof IntegrationsApiRoute
  '/integrations/edi': typeof IntegrationsEdiRoute
  '/integrations/health': typeof IntegrationsHealthRoute
  '/integrations/hub': typeof IntegrationsHubRoute
  '/integrations/webhooks': typeof IntegrationsWebhooksRoute
  '/intelligence/alerts': typeof IntelligenceAlertsRoute
  '/intelligence/capacity': typeof IntelligenceCapacityRoute
  '/intelligence/customers': typeof IntelligenceCustomersRoute
  '/intelligence/dispatch': typeof IntelligenceDispatchRoute
  '/intelligence/eta-confidence': typeof IntelligenceEtaConfidenceRoute
  '/intelligence/executive': typeof IntelligenceExecutiveRoute
  '/intelligence/governance': typeof IntelligenceGovernanceRoute
  '/intelligence/handoff': typeof IntelligenceHandoffRoute
  '/intelligence/overview': typeof IntelligenceOverviewRoute
  '/intelligence/phase9-overview': typeof IntelligencePhase9OverviewRoute
  '/intelligence/recommendations': typeof IntelligenceRecommendationsRoute
  '/intelligence/risk': typeof IntelligenceRiskRoute
  '/launch/demo': typeof LaunchDemoRoute
  '/launch/documentation': typeof LaunchDocumentationRoute
  '/launch/marketing': typeof LaunchMarketingRoute
  '/launch/onboarding': typeof LaunchOnboardingRoute
  '/launch/overview': typeof LaunchOverviewRoute
  '/launch/pilot': typeof LaunchPilotRoute
  '/launch/pricing': typeof LaunchPricingRoute
  '/launch/roi': typeof LaunchRoiRoute
  '/launch/sales': typeof LaunchSalesRoute
  '/ops/center': typeof OpsCenterRoute
  '/ops/database': typeof OpsDatabaseRoute
  '/ops/incidents': typeof OpsIncidentsRoute
  '/ops/observability': typeof OpsObservabilityRoute
  '/optimization/center': typeof OptimizationCenterRoute
  '/portal/new-request': typeof PortalNewRequestRoute
  '/rating/quote': typeof RatingQuoteRoute
  '/security/center': typeof SecurityCenterRoute
  '/security/overview': typeof SecurityOverviewRoute
  '/security/phase8-overview': typeof SecurityPhase8OverviewRoute
  '/security/privacy': typeof SecurityPrivacyRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/email-templates': typeof SettingsEmailTemplatesRoute
  '/settings/production': typeof SettingsProductionRoute
  '/settings/production-monitoring': typeof SettingsProductionMonitoringRoute
  '/settings/white-label': typeof SettingsWhiteLabelRoute
  '/driver': typeof DriverIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-change-password': typeof AdminChangePasswordRoute
  '/admin-login': typeof AdminLoginRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/dispatch': typeof DispatchRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/drivers': typeof DriversRoute
  '/fuel': typeof FuelRoute
  '/loads': typeof LoadsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/portal': typeof PortalRouteWithChildren
  '/routes': typeof RoutesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/shipments': typeof ShipmentsRoute
  '/signup': typeof SignupRoute
  '/vehicles': typeof VehiclesRoute
  '/admin/platform': typeof AdminPlatformRoute
  '/compliance/soc2': typeof ComplianceSoc2Route
  '/data/import-export': typeof DataImportExportRoute
  '/dispatch/command-center': typeof DispatchCommandCenterRoute
  '/driver/copilot-lab': typeof DriverCopilotLabRoute
  '/driver/deliveries': typeof DriverDeliveriesRoute
  '/driver/elite-nav': typeof DriverEliteNavRoute
  '/driver/elitenav': typeof DriverElitenavRoute
  '/driver/nav-lab': typeof DriverNavLabRoute
  '/driver/navigation': typeof DriverNavigationRoute
  '/driver/notifications-lab': typeof DriverNotificationsLabRoute
  '/driver/phase5-demo': typeof DriverPhase5DemoRoute
  '/enterprise/overview': typeof EnterpriseOverviewRoute
  '/enterprise/phase7-demo': typeof EnterprisePhase7DemoRoute
  '/integrations/api': typeof IntegrationsApiRoute
  '/integrations/edi': typeof IntegrationsEdiRoute
  '/integrations/health': typeof IntegrationsHealthRoute
  '/integrations/hub': typeof IntegrationsHubRoute
  '/integrations/webhooks': typeof IntegrationsWebhooksRoute
  '/intelligence/alerts': typeof IntelligenceAlertsRoute
  '/intelligence/capacity': typeof IntelligenceCapacityRoute
  '/intelligence/customers': typeof IntelligenceCustomersRoute
  '/intelligence/dispatch': typeof IntelligenceDispatchRoute
  '/intelligence/eta-confidence': typeof IntelligenceEtaConfidenceRoute
  '/intelligence/executive': typeof IntelligenceExecutiveRoute
  '/intelligence/governance': typeof IntelligenceGovernanceRoute
  '/intelligence/handoff': typeof IntelligenceHandoffRoute
  '/intelligence/overview': typeof IntelligenceOverviewRoute
  '/intelligence/phase9-overview': typeof IntelligencePhase9OverviewRoute
  '/intelligence/recommendations': typeof IntelligenceRecommendationsRoute
  '/intelligence/risk': typeof IntelligenceRiskRoute
  '/launch/demo': typeof LaunchDemoRoute
  '/launch/documentation': typeof LaunchDocumentationRoute
  '/launch/marketing': typeof LaunchMarketingRoute
  '/launch/onboarding': typeof LaunchOnboardingRoute
  '/launch/overview': typeof LaunchOverviewRoute
  '/launch/pilot': typeof LaunchPilotRoute
  '/launch/pricing': typeof LaunchPricingRoute
  '/launch/roi': typeof LaunchRoiRoute
  '/launch/sales': typeof LaunchSalesRoute
  '/ops/center': typeof OpsCenterRoute
  '/ops/database': typeof OpsDatabaseRoute
  '/ops/incidents': typeof OpsIncidentsRoute
  '/ops/observability': typeof OpsObservabilityRoute
  '/optimization/center': typeof OptimizationCenterRoute
  '/portal/new-request': typeof PortalNewRequestRoute
  '/rating/quote': typeof RatingQuoteRoute
  '/security/center': typeof SecurityCenterRoute
  '/security/overview': typeof SecurityOverviewRoute
  '/security/phase8-overview': typeof SecurityPhase8OverviewRoute
  '/security/privacy': typeof SecurityPrivacyRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/email-templates': typeof SettingsEmailTemplatesRoute
  '/settings/production': typeof SettingsProductionRoute
  '/settings/production-monitoring': typeof SettingsProductionMonitoringRoute
  '/settings/white-label': typeof SettingsWhiteLabelRoute
  '/driver/': typeof DriverIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-change-password'
    | '/admin-login'
    | '/alerts'
    | '/analytics'
    | '/dispatch'
    | '/documents'
    | '/drivers'
    | '/fuel'
    | '/loads'
    | '/login'
    | '/map'
    | '/portal'
    | '/routes'
    | '/settings'
    | '/shipments'
    | '/signup'
    | '/vehicles'
    | '/admin/platform'
    | '/compliance/soc2'
    | '/data/import-export'
    | '/dispatch/command-center'
    | '/driver/copilot-lab'
    | '/driver/deliveries'
    | '/driver/elite-nav'
    | '/driver/elitenav'
    | '/driver/nav-lab'
    | '/driver/navigation'
    | '/driver/notifications-lab'
    | '/driver/phase5-demo'
    | '/enterprise/overview'
    | '/enterprise/phase7-demo'
    | '/integrations/api'
    | '/integrations/edi'
    | '/integrations/health'
    | '/integrations/hub'
    | '/integrations/webhooks'
    | '/intelligence/alerts'
    | '/intelligence/capacity'
    | '/intelligence/customers'
    | '/intelligence/dispatch'
    | '/intelligence/eta-confidence'
    | '/intelligence/executive'
    | '/intelligence/governance'
    | '/intelligence/handoff'
    | '/intelligence/overview'
    | '/intelligence/phase9-overview'
    | '/intelligence/recommendations'
    | '/intelligence/risk'
    | '/launch/demo'
    | '/launch/documentation'
    | '/launch/marketing'
    | '/launch/onboarding'
    | '/launch/overview'
    | '/launch/pilot'
    | '/launch/pricing'
    | '/launch/roi'
    | '/launch/sales'
    | '/ops/center'
    | '/ops/database'
    | '/ops/incidents'
    | '/ops/observability'
    | '/optimization/center'
    | '/portal/new-request'
    | '/rating/quote'
    | '/security/center'
    | '/security/overview'
    | '/security/phase8-overview'
    | '/security/privacy'
    | '/settings/billing'
    | '/settings/email-templates'
    | '/settings/production'
    | '/settings/production-monitoring'
    | '/settings/white-label'
    | '/driver/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-change-password'
    | '/admin-login'
    | '/alerts'
    | '/analytics'
    | '/dispatch'
    | '/documents'
    | '/drivers'
    | '/fuel'
    | '/loads'
    | '/login'
    | '/map'
    | '/portal'
    | '/routes'
    | '/settings'
    | '/shipments'
    | '/signup'
    | '/vehicles'
    | '/admin/platform'
    | '/compliance/soc2'
    | '/data/import-export'
    | '/dispatch/command-center'
    | '/driver/copilot-lab'
    | '/driver/deliveries'
    | '/driver/elite-nav'
    | '/driver/elitenav'
    | '/driver/nav-lab'
    | '/driver/navigation'
    | '/driver/notifications-lab'
    | '/driver/phase5-demo'
    | '/enterprise/overview'
    | '/enterprise/phase7-demo'
    | '/integrations/api'
    | '/integrations/edi'
    | '/integrations/health'
    | '/integrations/hub'
    | '/integrations/webhooks'
    | '/intelligence/alerts'
    | '/intelligence/capacity'
    | '/intelligence/customers'
    | '/intelligence/dispatch'
    | '/intelligence/eta-confidence'
    | '/intelligence/executive'
    | '/intelligence/governance'
    | '/intelligence/handoff'
    | '/intelligence/overview'
    | '/intelligence/phase9-overview'
    | '/intelligence/recommendations'
    | '/intelligence/risk'
    | '/launch/demo'
    | '/launch/documentation'
    | '/launch/marketing'
    | '/launch/onboarding'
    | '/launch/overview'
    | '/launch/pilot'
    | '/launch/pricing'
    | '/launch/roi'
    | '/launch/sales'
    | '/ops/center'
    | '/ops/database'
    | '/ops/incidents'
    | '/ops/observability'
    | '/optimization/center'
    | '/portal/new-request'
    | '/rating/quote'
    | '/security/center'
    | '/security/overview'
    | '/security/phase8-overview'
    | '/security/privacy'
    | '/settings/billing'
    | '/settings/email-templates'
    | '/settings/production'
    | '/settings/production-monitoring'
    | '/settings/white-label'
    | '/driver'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-change-password'
    | '/admin-login'
    | '/alerts'
    | '/analytics'
    | '/dispatch'
    | '/documents'
    | '/drivers'
    | '/fuel'
    | '/loads'
    | '/login'
    | '/map'
    | '/portal'
    | '/routes'
    | '/settings'
    | '/shipments'
    | '/signup'
    | '/vehicles'
    | '/admin/platform'
    | '/compliance/soc2'
    | '/data/import-export'
    | '/dispatch/command-center'
    | '/driver/copilot-lab'
    | '/driver/deliveries'
    | '/driver/elite-nav'
    | '/driver/elitenav'
    | '/driver/nav-lab'
    | '/driver/navigation'
    | '/driver/notifications-lab'
    | '/driver/phase5-demo'
    | '/enterprise/overview'
    | '/enterprise/phase7-demo'
    | '/integrations/api'
    | '/integrations/edi'
    | '/integrations/health'
    | '/integrations/hub'
    | '/integrations/webhooks'
    | '/intelligence/alerts'
    | '/intelligence/capacity'
    | '/intelligence/customers'
    | '/intelligence/dispatch'
    | '/intelligence/eta-confidence'
    | '/intelligence/executive'
    | '/intelligence/governance'
    | '/intelligence/handoff'
    | '/intelligence/overview'
    | '/intelligence/phase9-overview'
    | '/intelligence/recommendations'
    | '/intelligence/risk'
    | '/launch/demo'
    | '/launch/documentation'
    | '/launch/marketing'
    | '/launch/onboarding'
    | '/launch/overview'
    | '/launch/pilot'
    | '/launch/pricing'
    | '/launch/roi'
    | '/launch/sales'
    | '/ops/center'
    | '/ops/database'
    | '/ops/incidents'
    | '/ops/observability'
    | '/optimization/center'
    | '/portal/new-request'
    | '/rating/quote'
    | '/security/center'
    | '/security/overview'
    | '/security/phase8-overview'
    | '/security/privacy'
    | '/settings/billing'
    | '/settings/email-templates'
    | '/settings/production'
    | '/settings/production-monitoring'
    | '/settings/white-label'
    | '/driver/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminChangePasswordRoute: typeof AdminChangePasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DispatchRoute: typeof DispatchRouteWithChildren
  DocumentsRoute: typeof DocumentsRoute
  DriversRoute: typeof DriversRoute
  FuelRoute: typeof FuelRoute
  LoadsRoute: typeof LoadsRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  PortalRoute: typeof PortalRouteWithChildren
  RoutesRoute: typeof RoutesRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ShipmentsRoute: typeof ShipmentsRoute
  SignupRoute: typeof SignupRoute
  VehiclesRoute: typeof VehiclesRoute
  ComplianceSoc2Route: typeof ComplianceSoc2Route
  DataImportExportRoute: typeof DataImportExportRoute
  DriverCopilotLabRoute: typeof DriverCopilotLabRoute
  DriverDeliveriesRoute: typeof DriverDeliveriesRoute
  DriverEliteNavRoute: typeof DriverEliteNavRoute
  DriverElitenavRoute: typeof DriverElitenavRoute
  DriverNavLabRoute: typeof DriverNavLabRoute
  DriverNavigationRoute: typeof DriverNavigationRoute
  DriverNotificationsLabRoute: typeof DriverNotificationsLabRoute
  DriverPhase5DemoRoute: typeof DriverPhase5DemoRoute
  EnterpriseOverviewRoute: typeof EnterpriseOverviewRoute
  EnterprisePhase7DemoRoute: typeof EnterprisePhase7DemoRoute
  IntegrationsApiRoute: typeof IntegrationsApiRoute
  IntegrationsEdiRoute: typeof IntegrationsEdiRoute
  IntegrationsHealthRoute: typeof IntegrationsHealthRoute
  IntegrationsHubRoute: typeof IntegrationsHubRoute
  IntegrationsWebhooksRoute: typeof IntegrationsWebhooksRoute
  IntelligenceAlertsRoute: typeof IntelligenceAlertsRoute
  IntelligenceCapacityRoute: typeof IntelligenceCapacityRoute
  IntelligenceCustomersRoute: typeof IntelligenceCustomersRoute
  IntelligenceDispatchRoute: typeof IntelligenceDispatchRoute
  IntelligenceEtaConfidenceRoute: typeof IntelligenceEtaConfidenceRoute
  IntelligenceExecutiveRoute: typeof IntelligenceExecutiveRoute
  IntelligenceGovernanceRoute: typeof IntelligenceGovernanceRoute
  IntelligenceHandoffRoute: typeof IntelligenceHandoffRoute
  IntelligenceOverviewRoute: typeof IntelligenceOverviewRoute
  IntelligencePhase9OverviewRoute: typeof IntelligencePhase9OverviewRoute
  IntelligenceRecommendationsRoute: typeof IntelligenceRecommendationsRoute
  IntelligenceRiskRoute: typeof IntelligenceRiskRoute
  LaunchDemoRoute: typeof LaunchDemoRoute
  LaunchDocumentationRoute: typeof LaunchDocumentationRoute
  LaunchMarketingRoute: typeof LaunchMarketingRoute
  LaunchOnboardingRoute: typeof LaunchOnboardingRoute
  LaunchOverviewRoute: typeof LaunchOverviewRoute
  LaunchPilotRoute: typeof LaunchPilotRoute
  LaunchPricingRoute: typeof LaunchPricingRoute
  LaunchRoiRoute: typeof LaunchRoiRoute
  LaunchSalesRoute: typeof LaunchSalesRoute
  OpsCenterRoute: typeof OpsCenterRoute
  OpsDatabaseRoute: typeof OpsDatabaseRoute
  OpsIncidentsRoute: typeof OpsIncidentsRoute
  OpsObservabilityRoute: typeof OpsObservabilityRoute
  OptimizationCenterRoute: typeof OptimizationCenterRoute
  RatingQuoteRoute: typeof RatingQuoteRoute
  SecurityCenterRoute: typeof SecurityCenterRoute
  SecurityOverviewRoute: typeof SecurityOverviewRoute
  SecurityPhase8OverviewRoute: typeof SecurityPhase8OverviewRoute
  SecurityPrivacyRoute: typeof SecurityPrivacyRoute
  DriverIndexRoute: typeof DriverIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loads': {
      id: '/loads'
      path: '/loads'
      fullPath: '/loads'
      preLoaderRoute: typeof LoadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuel': {
      id: '/fuel'
      path: '/fuel'
      fullPath: '/fuel'
      preLoaderRoute: typeof FuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-change-password': {
      id: '/admin-change-password'
      path: '/admin-change-password'
      fullPath: '/admin-change-password'
      preLoaderRoute: typeof AdminChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/driver'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/white-label': {
      id: '/settings/white-label'
      path: '/white-label'
      fullPath: '/settings/white-label'
      preLoaderRoute: typeof SettingsWhiteLabelRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/production-monitoring': {
      id: '/settings/production-monitoring'
      path: '/production-monitoring'
      fullPath: '/settings/production-monitoring'
      preLoaderRoute: typeof SettingsProductionMonitoringRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/production': {
      id: '/settings/production'
      path: '/production'
      fullPath: '/settings/production'
      preLoaderRoute: typeof SettingsProductionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/email-templates': {
      id: '/settings/email-templates'
      path: '/email-templates'
      fullPath: '/settings/email-templates'
      preLoaderRoute: typeof SettingsEmailTemplatesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/security/privacy': {
      id: '/security/privacy'
      path: '/security/privacy'
      fullPath: '/security/privacy'
      preLoaderRoute: typeof SecurityPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/phase8-overview': {
      id: '/security/phase8-overview'
      path: '/security/phase8-overview'
      fullPath: '/security/phase8-overview'
      preLoaderRoute: typeof SecurityPhase8OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/overview': {
      id: '/security/overview'
      path: '/security/overview'
      fullPath: '/security/overview'
      preLoaderRoute: typeof SecurityOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/center': {
      id: '/security/center'
      path: '/security/center'
      fullPath: '/security/center'
      preLoaderRoute: typeof SecurityCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating/quote': {
      id: '/rating/quote'
      path: '/rating/quote'
      fullPath: '/rating/quote'
      preLoaderRoute: typeof RatingQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/new-request': {
      id: '/portal/new-request'
      path: '/new-request'
      fullPath: '/portal/new-request'
      preLoaderRoute: typeof PortalNewRequestRouteImport
      parentRoute: typeof PortalRoute
    }
    '/optimization/center': {
      id: '/optimization/center'
      path: '/optimization/center'
      fullPath: '/optimization/center'
      preLoaderRoute: typeof OptimizationCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/observability': {
      id: '/ops/observability'
      path: '/ops/observability'
      fullPath: '/ops/observability'
      preLoaderRoute: typeof OpsObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/incidents': {
      id: '/ops/incidents'
      path: '/ops/incidents'
      fullPath: '/ops/incidents'
      preLoaderRoute: typeof OpsIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/database': {
      id: '/ops/database'
      path: '/ops/database'
      fullPath: '/ops/database'
      preLoaderRoute: typeof OpsDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/center': {
      id: '/ops/center'
      path: '/ops/center'
      fullPath: '/ops/center'
      preLoaderRoute: typeof OpsCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch/sales': {
      id: '/launch/sales'
      path: '/launch/sales'
      fullPath: '/launch/sales'
      preLoaderRoute: typeof LaunchSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch/roi': {
      id: '/launch/roi'
      path: '/launch/roi'
      fullPath: '/launch/roi'
      preLoaderRoute: typeof LaunchRoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch/pricing': {
      id: '/launch/pricing'
      path: '/launch/pricing'
      fullPath: '/launch/pricing'
      preLoaderRoute: typeof LaunchPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch/pilot': {
      id: '/launch/pilot'
      path: '/launch/pilot'
      fullPath: '/launch/pilot'
      preLoaderRoute: typeof LaunchPilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch/overview': {
      id: '/launch/overview'
      path: '/launch/overview'
      fullPath: '/launch/overview'
      preLoaderRoute: typeof LaunchOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch/onboarding': {
      id: '/launch/onboarding'
      path: '/launch/onboarding'
      fullPath: '/launch/onboarding'
      preLoaderRoute: typeof LaunchOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch/marketing': {
      id: '/launch/marketing'
      path: '/launch/marketing'
      fullPath: '/launch/marketing'
      preLoaderRoute: typeof LaunchMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch/documentation': {
      id: '/launch/documentation'
      path: '/launch/documentation'
      fullPath: '/launch/documentation'
      preLoaderRoute: typeof LaunchDocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch/demo': {
      id: '/launch/demo'
      path: '/launch/demo'
      fullPath: '/launch/demo'
      preLoaderRoute: typeof LaunchDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence/risk': {
      id: '/intelligence/risk'
      path: '/intelligence/risk'
      fullPath: '/intelligence/risk'
      preLoaderRoute: typeof IntelligenceRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence/recommendations': {
      id: '/intelligence/recommendations'
      path: '/intelligence/recommendations'
      fullPath: '/intelligence/recommendations'
      preLoaderRoute: typeof IntelligenceRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence/phase9-overview': {
      id: '/intelligence/phase9-overview'
      path: '/intelligence/phase9-overview'
      fullPath: '/intelligence/phase9-overview'
      preLoaderRoute: typeof IntelligencePhase9OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence/overview': {
      id: '/intelligence/overview'
      path: '/intelligence/overview'
      fullPath: '/intelligence/overview'
      preLoaderRoute: typeof IntelligenceOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence/handoff': {
      id: '/intelligence/handoff'
      path: '/intelligence/handoff'
      fullPath: '/intelligence/handoff'
      preLoaderRoute: typeof IntelligenceHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence/governance': {
      id: '/intelligence/governance'
      path: '/intelligence/governance'
      fullPath: '/intelligence/governance'
      preLoaderRoute: typeof IntelligenceGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence/executive': {
      id: '/intelligence/executive'
      path: '/intelligence/executive'
      fullPath: '/intelligence/executive'
      preLoaderRoute: typeof IntelligenceExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence/eta-confidence': {
      id: '/intelligence/eta-confidence'
      path: '/intelligence/eta-confidence'
      fullPath: '/intelligence/eta-confidence'
      preLoaderRoute: typeof IntelligenceEtaConfidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence/dispatch': {
      id: '/intelligence/dispatch'
      path: '/intelligence/dispatch'
      fullPath: '/intelligence/dispatch'
      preLoaderRoute: typeof IntelligenceDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence/customers': {
      id: '/intelligence/customers'
      path: '/intelligence/customers'
      fullPath: '/intelligence/customers'
      preLoaderRoute: typeof IntelligenceCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence/capacity': {
      id: '/intelligence/capacity'
      path: '/intelligence/capacity'
      fullPath: '/intelligence/capacity'
      preLoaderRoute: typeof IntelligenceCapacityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence/alerts': {
      id: '/intelligence/alerts'
      path: '/intelligence/alerts'
      fullPath: '/intelligence/alerts'
      preLoaderRoute: typeof IntelligenceAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/webhooks': {
      id: '/integrations/webhooks'
      path: '/integrations/webhooks'
      fullPath: '/integrations/webhooks'
      preLoaderRoute: typeof IntegrationsWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/hub': {
      id: '/integrations/hub'
      path: '/integrations/hub'
      fullPath: '/integrations/hub'
      preLoaderRoute: typeof IntegrationsHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/health': {
      id: '/integrations/health'
      path: '/integrations/health'
      fullPath: '/integrations/health'
      preLoaderRoute: typeof IntegrationsHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/edi': {
      id: '/integrations/edi'
      path: '/integrations/edi'
      fullPath: '/integrations/edi'
      preLoaderRoute: typeof IntegrationsEdiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/api': {
      id: '/integrations/api'
      path: '/integrations/api'
      fullPath: '/integrations/api'
      preLoaderRoute: typeof IntegrationsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise/phase7-demo': {
      id: '/enterprise/phase7-demo'
      path: '/enterprise/phase7-demo'
      fullPath: '/enterprise/phase7-demo'
      preLoaderRoute: typeof EnterprisePhase7DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise/overview': {
      id: '/enterprise/overview'
      path: '/enterprise/overview'
      fullPath: '/enterprise/overview'
      preLoaderRoute: typeof EnterpriseOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/phase5-demo': {
      id: '/driver/phase5-demo'
      path: '/driver/phase5-demo'
      fullPath: '/driver/phase5-demo'
      preLoaderRoute: typeof DriverPhase5DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/notifications-lab': {
      id: '/driver/notifications-lab'
      path: '/driver/notifications-lab'
      fullPath: '/driver/notifications-lab'
      preLoaderRoute: typeof DriverNotificationsLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/navigation': {
      id: '/driver/navigation'
      path: '/driver/navigation'
      fullPath: '/driver/navigation'
      preLoaderRoute: typeof DriverNavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/nav-lab': {
      id: '/driver/nav-lab'
      path: '/driver/nav-lab'
      fullPath: '/driver/nav-lab'
      preLoaderRoute: typeof DriverNavLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/elitenav': {
      id: '/driver/elitenav'
      path: '/driver/elitenav'
      fullPath: '/driver/elitenav'
      preLoaderRoute: typeof DriverElitenavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/elite-nav': {
      id: '/driver/elite-nav'
      path: '/driver/elite-nav'
      fullPath: '/driver/elite-nav'
      preLoaderRoute: typeof DriverEliteNavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/deliveries': {
      id: '/driver/deliveries'
      path: '/driver/deliveries'
      fullPath: '/driver/deliveries'
      preLoaderRoute: typeof DriverDeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/copilot-lab': {
      id: '/driver/copilot-lab'
      path: '/driver/copilot-lab'
      fullPath: '/driver/copilot-lab'
      preLoaderRoute: typeof DriverCopilotLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch/command-center': {
      id: '/dispatch/command-center'
      path: '/command-center'
      fullPath: '/dispatch/command-center'
      preLoaderRoute: typeof DispatchCommandCenterRouteImport
      parentRoute: typeof DispatchRoute
    }
    '/data/import-export': {
      id: '/data/import-export'
      path: '/data/import-export'
      fullPath: '/data/import-export'
      preLoaderRoute: typeof DataImportExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/soc2': {
      id: '/compliance/soc2'
      path: '/compliance/soc2'
      fullPath: '/compliance/soc2'
      preLoaderRoute: typeof ComplianceSoc2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/platform': {
      id: '/admin/platform'
      path: '/platform'
      fullPath: '/admin/platform'
      preLoaderRoute: typeof AdminPlatformRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminPlatformRoute: typeof AdminPlatformRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPlatformRoute: AdminPlatformRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DispatchRouteChildren {
  DispatchCommandCenterRoute: typeof DispatchCommandCenterRoute
}

const DispatchRouteChildren: DispatchRouteChildren = {
  DispatchCommandCenterRoute: DispatchCommandCenterRoute,
}

const DispatchRouteWithChildren = DispatchRoute._addFileChildren(
  DispatchRouteChildren,
)

interface PortalRouteChildren {
  PortalNewRequestRoute: typeof PortalNewRequestRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalNewRequestRoute: PortalNewRequestRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface SettingsRouteChildren {
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsEmailTemplatesRoute: typeof SettingsEmailTemplatesRoute
  SettingsProductionRoute: typeof SettingsProductionRoute
  SettingsProductionMonitoringRoute: typeof SettingsProductionMonitoringRoute
  SettingsWhiteLabelRoute: typeof SettingsWhiteLabelRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsEmailTemplatesRoute: SettingsEmailTemplatesRoute,
  SettingsProductionRoute: SettingsProductionRoute,
  SettingsProductionMonitoringRoute: SettingsProductionMonitoringRoute,
  SettingsWhiteLabelRoute: SettingsWhiteLabelRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminChangePasswordRoute: AdminChangePasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  DispatchRoute: DispatchRouteWithChildren,
  DocumentsRoute: DocumentsRoute,
  DriversRoute: DriversRoute,
  FuelRoute: FuelRoute,
  LoadsRoute: LoadsRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  PortalRoute: PortalRouteWithChildren,
  RoutesRoute: RoutesRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ShipmentsRoute: ShipmentsRoute,
  SignupRoute: SignupRoute,
  VehiclesRoute: VehiclesRoute,
  ComplianceSoc2Route: ComplianceSoc2Route,
  DataImportExportRoute: DataImportExportRoute,
  DriverCopilotLabRoute: DriverCopilotLabRoute,
  DriverDeliveriesRoute: DriverDeliveriesRoute,
  DriverEliteNavRoute: DriverEliteNavRoute,
  DriverElitenavRoute: DriverElitenavRoute,
  DriverNavLabRoute: DriverNavLabRoute,
  DriverNavigationRoute: DriverNavigationRoute,
  DriverNotificationsLabRoute: DriverNotificationsLabRoute,
  DriverPhase5DemoRoute: DriverPhase5DemoRoute,
  EnterpriseOverviewRoute: EnterpriseOverviewRoute,
  EnterprisePhase7DemoRoute: EnterprisePhase7DemoRoute,
  IntegrationsApiRoute: IntegrationsApiRoute,
  IntegrationsEdiRoute: IntegrationsEdiRoute,
  IntegrationsHealthRoute: IntegrationsHealthRoute,
  IntegrationsHubRoute: IntegrationsHubRoute,
  IntegrationsWebhooksRoute: IntegrationsWebhooksRoute,
  IntelligenceAlertsRoute: IntelligenceAlertsRoute,
  IntelligenceCapacityRoute: IntelligenceCapacityRoute,
  IntelligenceCustomersRoute: IntelligenceCustomersRoute,
  IntelligenceDispatchRoute: IntelligenceDispatchRoute,
  IntelligenceEtaConfidenceRoute: IntelligenceEtaConfidenceRoute,
  IntelligenceExecutiveRoute: IntelligenceExecutiveRoute,
  IntelligenceGovernanceRoute: IntelligenceGovernanceRoute,
  IntelligenceHandoffRoute: IntelligenceHandoffRoute,
  IntelligenceOverviewRoute: IntelligenceOverviewRoute,
  IntelligencePhase9OverviewRoute: IntelligencePhase9OverviewRoute,
  IntelligenceRecommendationsRoute: IntelligenceRecommendationsRoute,
  IntelligenceRiskRoute: IntelligenceRiskRoute,
  LaunchDemoRoute: LaunchDemoRoute,
  LaunchDocumentationRoute: LaunchDocumentationRoute,
  LaunchMarketingRoute: LaunchMarketingRoute,
  LaunchOnboardingRoute: LaunchOnboardingRoute,
  LaunchOverviewRoute: LaunchOverviewRoute,
  LaunchPilotRoute: LaunchPilotRoute,
  LaunchPricingRoute: LaunchPricingRoute,
  LaunchRoiRoute: LaunchRoiRoute,
  LaunchSalesRoute: LaunchSalesRoute,
  OpsCenterRoute: OpsCenterRoute,
  OpsDatabaseRoute: OpsDatabaseRoute,
  OpsIncidentsRoute: OpsIncidentsRoute,
  OpsObservabilityRoute: OpsObservabilityRoute,
  OptimizationCenterRoute: OptimizationCenterRoute,
  RatingQuoteRoute: RatingQuoteRoute,
  SecurityCenterRoute: SecurityCenterRoute,
  SecurityOverviewRoute: SecurityOverviewRoute,
  SecurityPhase8OverviewRoute: SecurityPhase8OverviewRoute,
  SecurityPrivacyRoute: SecurityPrivacyRoute,
  DriverIndexRoute: DriverIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
